### ISSUE TITLE
Adding dialyzer, credo, boundary checks

### ISSUE THREAD

**Issue by Nezteb** [btkostner/jumar#26]
I randomly found this project and noticed this bit of the README:

> 🟨 Code linting via `dialyzer`
> 🟨 Code linting via `credo`
> 🟨 Code linting via `boundary`

Regarding each:
- `dialyzer`
  - [I can assist with this!](https://fly.io/phoenix-files/adding-dialyzer-without-the-pain/)
- `credo`
  - I can assist with this!
- `boundary`
  - I've never actually used `boundary` but I've been wanting to try, so I'd like to also assist with this.

Granted, me doing any of this will probably wait until a few months into the new year. 😄

**Comment by btkostner** [comment]
Alrighty, took a while to get back into this project but all 3 of those are now integrated in 🎊
